### ISSUE TITLE
Degraded mount

### ISSUE THREAD

**Issue by hahnjo** [anthonyrisinger/mkinitcpio-btrfs#10]
I just tried this hook, it's working great!

I have one question: To make the degraded mount work, is it possible that one has to add the degraded option to fstab?
This does not get clear from the documentation, but it was the only way I could get it to work.

**Comment by visit1985** [comment]
You just need to uncomment BTRFS_ENABLE_DEGRADED=true in /etc/default/btrfs_advanced and regenerate your initrd. The hook then tries to mount without degraded option first. If this failes it tries to mount with degraded option.

Nothing to add to fstab, as fstab is not present while mounting the root filesystem.
