### ISSUE TITLE
grub rescue after clean install

### ISSUE THREAD

**Issue by anthonyrisinger** [anthonyrisinger/mkinitcpio-btrfs#3]
from https://aur.archlinux.org/packages/mkinitcpio-btrfs/ user `kodiak`:

> now I am sure that my problem depends on this hook. While I got my old notebook
> working, I did a fresh install on my htpc. All good until I installed this hook -> grub
> rescue, and even passing the right paths the system would insist on rebooting. To get
> it working again, I needed actual to reinstall the grub package, no just installing the
> bootloader again.

**Comment by visit1985** [comment]
@xtfxme: I'm watching the AUR comments now. This issue is related to the new set-default mechanism used in 0.4. In result of that, the kernel is found under '/boot' instead of '/__active/boot'.

**Comment by visit1985** [comment]
Updated the arch wiki page for that too.

**Comment by anthonyrisinger** [comment]
awesome @visit1985 -- thanks for putting some time into this hook, and also updating the wiki page -- much appreciated! LMK when you need the AUR updated.

if all goes well for awhile, and you have the interest, we can explore transferring project control to you; im almost ashamed to admit that i haven't actually used btrfs for 2+ years -- i had a hiccup awhile back (my own fault) and had to revert to ext4 for normal use... so while i fully expect to use btrfs eventually, and probably soon, i don't know when that will be exactly, so i'm simply not the best person for the job anymore.

**Comment by visit1985** [comment]
@xtfxme: I don't want to take it away from you. I just implement the features I need for personal interest, and try to support as my spare time allows.

I never submitted a AUR package, and for that don't know if that is even possible. But if you don't mind, you can give me co-ownership in AUR, so I can update it with small fixes like that. Beside that I will continue to open pull requests for the sake of discussing new features before merging them.

[edit] Forgot: Yes... you can update the AUR package ;-)

**Comment by anthonyrisinger** [comment]
Heh... Fair enough.  Tbh I was hoping you _wanted_ to take it off my hands as I've other projects/interests I'm currently pursuing :)

No worries, we'll just do things one at a time and see what happens.  I'll update the AUR package later tonight.

**Comment by visit1985** [comment]
Maybe I'll do that someday, but at the current state I appreciate a second pair of eyes, looking on the code before it is published ;)
