### ISSUE TITLE
Remove rollback dialog from boot?

### ISSUE THREAD

**Issue by visit1985** [anthonyrisinger/mkinitcpio-btrfs#9]
@xtfxme,

I'm using the hook on my notebook for more than 6 months now. In all this time, I never used the rollback dialog provided in the init script. I caught my self many times by just moving the __active subvolume to __active.old and copy a snapshot to __active before rebooting.

The Kernel version check introduced in 32ddc81 works very well for me through, so I don't want to miss that. We should make this enabled by default now.

But I seriously want to ask, if we should remove the rollback dialog, or at least make it optional, because it bugs me, that the boot process takes the most time waiting for a key-press in our hook :)

There are only 3 possible scenarios what can happen on boot:
1) The root-fs is not mountable for some reason - our hook is useless here, as the kernel could not be loaded by grub either (happend once for me)
2) The root-fs is mountable either normal or degraded and our hook will boot as normal (maybe we kexec to another kernel)
3) The root-fs is mountable, but the hook is failing - this drops us into initrd, which has btrfs included, so we can fix our setup and reboot

So for advanced user (like me) there is no need for a boot dialog.
What do you think?

P.S.: By the way, our [arch wiki article](https://wiki.archlinux.org/index.php?title=Mkinitcpio-btrfs&oldid=281459) was completely screwed up by some other users. I don't know, if we should update it again. I'm actually not in the mood to do it again :(

**Comment by anthonyrisinger** [comment]
i don't know about dropping it, but making it configurable and dropping the default to a second or so seems reasonable. eventually it would be nice to include a tiny tool for making a snapshot and swapping `__active`.

i'm cool with enabling the kernel stuffs by default.

pity about the wiki page though :( i've fixed that a couple times myself, and at one point it looked pretty solid... downright exceptional by current standards.
